{{- if and .Values.autoscaling.api.enabled (or .Values.autoscaling.rmq.enabled .Values.autoscaling.cron.enabled) }}
{{- $name := include "smartface.authApi.name" . -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
# TODO these as well
  name: {{ $name | quote }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name | quote }}
  minReplicaCount: {{ .Values.autoscaling.api.minReplicas }}
  maxReplicaCount: {{ .Values.autoscaling.api.maxReplicas }}
  triggers:
  {{- if .Values.autoscaling.rmq.enabled }}
  - type: "rabbitmq"
    metadata:
      queueName: "rpc\\.face\\.detect.*"
      mode: "MessageRate"
      value: {{ .Values.autoscaling.api.rmqRps | quote }}
      useRegex: "true"
    authenticationRef:
      name: {{ .Values.autoscaling.rmq.triggerAuthName | quote }}
  {{- end }}
  {{- if .Values.autoscaling.cron.enabled }}
#   during work hours
  - type: "cron"
    metadata:
      timezone: {{ .Values.autoscaling.cron.timezone | quote }}
      start: "0 8 * * 1-5"
      end: "0 17 * * 1-5"
      desiredReplicas: {{ .Values.autoscaling.api.workHoursReplicas | quote }}
#   outside work hours
  - type: "cron"
    metadata:
      timezone: {{ .Values.autoscaling.cron.timezone | quote }}
      start: "0 17 * * 1-5"
      end: "0 8 * * 1-5"
      desiredReplicas: {{ .Values.autoscaling.api.nonWorkHoursReplicas | quote }}
#   during weekend
  - type: "cron"
    metadata:
      timezone: {{ .Values.autoscaling.cron.timezone | quote }}
      start: "0 0 * * 0,6"
      end: "0 0 * * 1-5"
      desiredReplicas: {{ .Values.autoscaling.api.nonWorkHoursReplicas | quote }}
  {{- end }}
{{- end }}
