{{- if .Values.metrics.monitoring.enabled }}
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: "sf-monitor"
  labels:
    {{- toYaml $.Values.metrics.monitoring.monitorDiscoveryLabel | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- toYaml $.Values.metrics.monitoring.serviceDiscoveryLabels | nindent 6 }}
  endpoints:
  - {{- if not .Values.metrics.monitoring.publishAllMetrics }}
    metricRelabelings:
      - action: drop
        regex: http_server_duration_ms_bucket
        sourceLabels:
          - __name__
      - action: drop
        regex: rpc_client_duration_ms_bucket
        sourceLabels:
          - __name__
    {{- end }}
    port: {{ .Values.metrics.monitoring.portName | quote }}
{{- end }}
