apiVersion: v2
name: smartface
description: SmartFace is a Scalable Facial Recognition Server Platform Able to Process Multiple Real-Time Video Streams. Currently the helm chart supports edge stream and Lightweight Face Identification System (LFIS) deployments

dependencies:
  - name: sf-tenant-management
    version: "0.4.4"
    repository: "oci://ghcr.io/innovatrics/sf-helm"
    condition: sf-tenant-management.enabled
  - name: rabbitmq
    version: "12.0.4"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: rabbitmq.enabled
  - name: minio
    version: "12.8.15"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: minio.enabled
  - name: postgresql
    version: "13.2.1"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: postgresql.enabled

type: application

keywords:
  - Face recognition
  - Biometrics

sources:
  - https://github.com/innovatrics/sf-helm
  - https://github.com/innovatrics/smartface

home: https://www.innovatrics.com/face-recognition-solutions/

maintainers:
  - name: Innovatrics
    url: https://www.innovatrics.com/

version: 0.8.13

appVersion: "v5_4.33.0"
