rabbitmq:
  persistence:
    enabled: false
postgresql:
  primary:
    persistence:
      enabled: false
minio:
  persistence:
    enabled: false

api:
  resources: null
authApi:
  resources: null
graphqlApi:
  resources: null
detector:
  resources: null
extractor:
  resources: null
matcher:
  resources: null
liveness:
  resources: null
