rabbitmq:
  persistence:
    enabled: false
postgresql:
  primary:
    persistence:
      enabled: false
minio:
  persistence:
    enabled: false
# We enabled edge streams so we can run all of the tests in one go with all features enabled
features:
  edgeStreams:
    enabled: true

api:
  resources: null
authApi:
  resources: null
graphqlApi:
  resources: null
detector:
  resources: null
extractor:
  resources: null
matcher:
  resources: null
liveness:
  resources: null
