{{- $predefinedTriggerUsed := (or .Values.autoscaling.rmq.enabled .Values.autoscaling.cron.enabled) -}}
{{- $customTriggerUsed := .Values.autoscaling.api.triggers -}}
{{- if and .Values.autoscaling.api.enabled (or $predefinedTriggerUsed $customTriggerUsed) }}
{{- $name := include "smartface.authApi.name" . -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ $name | quote }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name | quote }}
  minReplicaCount: {{ .Values.autoscaling.api.minReplicas }}
  maxReplicaCount: {{ .Values.autoscaling.api.maxReplicas }}
  triggers:
  {{- if .Values.autoscaling.rmq.enabled }}
  - type: "rabbitmq"
    metadata:
      queueName: "rpc\\.face\\.detect.*"
      mode: "MessageRate"
      value: {{ .Values.autoscaling.rmq.api.requestsPerSecond | quote }}
      useRegex: "true"
    authenticationRef:
      name: {{ .Values.autoscaling.rmq.triggerAuthName | quote }}
  {{- end }}
  {{- if .Values.autoscaling.cron.enabled }}
#   during work hours
  - type: "cron"
    metadata:
      timezone: {{ .Values.autoscaling.cron.timezone | quote }}
      start: {{ .Values.autoscaling.cron.schedules.workHours.start | quote }}
      end: {{ .Values.autoscaling.cron.schedules.workHours.end | quote }}
      desiredReplicas: {{ .Values.autoscaling.cron.api.workHoursReplicas | quote }}
#   outside work hours
  - type: "cron"
    metadata:
      timezone: {{ .Values.autoscaling.cron.timezone | quote }}
      start: {{ .Values.autoscaling.cron.schedules.nonWorkHours.start | quote }}
      end: {{ .Values.autoscaling.cron.schedules.nonWorkHours.end | quote }}
      desiredReplicas: {{ .Values.autoscaling.cron.api.nonWorkHoursReplicas | quote }}
#   during weekend
  - type: "cron"
    metadata:
      timezone: {{ .Values.autoscaling.cron.timezone | quote }}
      start: {{ .Values.autoscaling.cron.schedules.weekend.start | quote }}
      end: {{ .Values.autoscaling.cron.schedules.weekend.end | quote }}
      desiredReplicas: {{ .Values.autoscaling.cron.api.nonWorkHoursReplicas | quote }}
  {{- end }}
  {{- with .Values.autoscaling.api.triggers }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
