{{- if .Values.autoscaling.rmq.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.autoscaling.rmq.hostSecretName | quote }}
type: Opaque
stringData:
  host: "http://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password | urlquery }}@{{ .Release.Name }}-rabbitmq.{{ .Release.Namespace }}.svc.cluster.local:15672"
{{- end }}
