{{- if and .Values.features.edgeStreams.enabled .Values.rabbitmq.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.rabbitmq.mqttConfigMapName | quote }}
data:
  hostname: "{{ .Release.Name }}-rabbitmq.{{ .Release.Namespace }}.svc.cluster.local"
  username: {{ .Values.rabbitmq.auth.username | quote }}
  port: "1883"
  useSsl: "false"
{{- end }}
