{{- if and .Values.readonlyApi.enabled .Values.api.enabled  }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.readonlyApi.noAuthName | quote }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    type: {{ .Values.updateStrategy.type }}
  selector:
    matchLabels:
      app: {{ .Values.readonlyApi.noAuthName | quote }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.readonlyApi.noAuthName | quote }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | quote }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      containers:
      - name: nginx
        image: nginx:1.25.1
        ports:
        - name: "http"
          containerPort: {{ .Values.api.containerPort }}
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
          readOnly: true
        resources:
          {{- toYaml .Values.readonlyApi.proxyContainer.resources | nindent 10 }}
      volumes:
      - name: nginx-conf
        configMap:
          name: {{ .Values.readonlyApi.noAuthName | quote }}
          items:
            - key: nginx.conf
              path: nginx.conf
{{- end }}
