{{- if and .Values.readonlyApi.enabled .Values.authApi.enabled }}
apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ .Values.readonlyApi.authName | quote }}
spec:
  selector:
    app: {{ .Values.readonlyApi.authName | quote }}
  ports:
    - name: "http"
      port: {{ .Values.authApi.servicePort }}
      targetPort: {{ .Values.authApi.containerPort }}
  type: "ClusterIP"
{{- end }}
