{{- if and .Values.features.offlineVideoProcessing.enabled .Values.VideoReader.pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "smartface.VideoReader.name" . | quote }}
  labels:
    {{- include "smartface.VideoReader.labels" . | nindent 4 }}
spec:
  {{- if .Values.VideoReader.pdb.minAvailable }}
  minAvailable: {{ .Values.VideoReader.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.VideoReader.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.VideoReader.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "smartface.VideoReader.selectorLabels" . | nindent 6 }}
{{- end }}
