{{- if .Values.api.enabled }}
apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "smartface.api.name" . | quote }}
  labels:
    {{- include "smartface.api.labels" . | nindent 4 }}
    {{- with .Values.serviceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.api.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.metrics.monitoring.serviceDiscoveryLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.api.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    {{- include "smartface.api.selectorLabels" . | nindent 4 }}
  ports:
    - name: "http"
      port: {{ .Values.api.servicePort }}
      targetPort: {{ .Values.api.containerPort }}
    - name: {{ .Values.metrics.monitoring.portName | quote }}
      port: {{ .Values.metrics.monitoring.port }}
  type: "ClusterIP"
{{- end }}
