{{- if .Values.api.enabled }}
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ .Values.api.name | quote }}
  labels:
    app: {{ .Values.api.name | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.api.name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.name | quote }}
    spec:
      topologySpreadConstraints:
        {{- include "sf-cloud-matcher.topologySpread" (dict "appLabel" .Values.api.name) | nindent 8 }}
      imagePullSecrets:
      - name: {{ .Values.image.secretName | quote }}
      containers:
      - name: {{ .Values.api.name | quote }}
        image: "{{ .Values.image.registry }}sf-api:{{ .Chart.AppVersion }}"
        ports:
        - name: "http"
          containerPort: {{ .Values.api.containerPort }}
        - name: {{ .Values.metrics.portName | quote }}
          containerPort: {{ .Values.metrics.port }}
        env:
        {{- include "sf-cloud-matcher.commonEnv" . | nindent 8 }}
        {{- include "sf-cloud-matcher.dbConfig" . | nindent 8 }}
        {{- include "sf-cloud-matcher.s3Config" . | nindent 8 }}
        {{- include "sf-cloud-matcher.rmqConfig" . | nindent 8 }}
        {{- include "sf-cloud-matcher.apiFeaturesConfig" . | nindent 8 }}
        {{- include "sf-cloud-matcher.statisticsPublish" . | nindent 8 }}
        - name: "Hosting__Host"
          value: "http://0.0.0.0"
        - name: "Hosting__Port"
          value: {{ .Values.api.containerPort | quote }}
        resources:
          requests:
            memory: "300M"
            cpu: "250m"
          limits:
            memory: "4G"
        volumeMounts:
        {{- include "sf-cloud-matcher.licVolumeMount" . | nindent 8 }}
      {{- if and .Values.migration.enabled .Values.api.initMigration }}
      initContainers:
      {{- include "sf-cloud-matcher.migrationInitContainer" . | nindent 6 }}
      {{- end }}
      volumes:
        {{- include "sf-cloud-matcher.licVolume" . | nindent 8 }}
{{- end }}
