{{- if .Values.api.enabled }}
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ .Values.api.name | quote }}
  labels:
    app: {{ .Values.api.name | quote }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.api.name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.name | quote }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | quote }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      topologySpreadConstraints:
        {{- include "smartface.topologySpread" (dict "appLabel" .Values.api.name) | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Values.api.name | quote }}
        image: {{ include "smartface.image" (dict "local" .Values.api.image "global" .Values.global.image "defaultVersion" .Chart.AppVersion) }}
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        ports:
        - name: "http"
          containerPort: {{ .Values.api.containerPort }}
        - name: {{ .Values.metrics.portName | quote }}
          containerPort: {{ .Values.metrics.port }}
        env:
        {{- include "smartface.commonEnv" . | nindent 8 }}
        {{- include "smartface.dbConfig" . | nindent 8 }}
        {{- include "smartface.s3Config" . | nindent 8 }}
        {{- include "smartface.rmqConfig" . | nindent 8 }}
        {{- include "smartface.apiFeaturesConfig" . | nindent 8 }}
        {{- include "smartface.statisticsPublish" . | nindent 8 }}
        - name: "Hosting__Host"
          value: "http://0.0.0.0"
        - name: "Hosting__Port"
          value: {{ .Values.api.containerPort | quote }}
        resources:
          {{- toYaml .Values.api.resources | nindent 10 }}
        volumeMounts:
        {{- include "smartface.licVolumeMount" . | nindent 8 }}
      {{- if and .Values.migration.enabled .Values.api.initMigration }}
      initContainers:
      {{- include "smartface.migrationInitContainer" . | nindent 6 }}
      {{- end }}
      volumes:
        {{- include "smartface.licVolume" . | nindent 8 }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
