{{- if .Values.api.enabled }}
{{- $name := include "smartface.api.name" . -}}
{{- $selectorLabels := include "smartface.api.selectorLabels" . -}}
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ $name | quote }}
  labels:
    {{- include "smartface.api.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.api.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      {{- $selectorLabels | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.api.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- $selectorLabels | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.api.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | quote }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      topologySpreadConstraints:
        {{- include "smartface.topologySpread" (dict "selectorLabels" $selectorLabels ) | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ $name | quote }}
        image: {{ include "smartface.image" (dict "local" .Values.api.image "global" .Values.global.image "defaultVersion" .Chart.AppVersion) }}
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        ports:
        - name: "http"
          containerPort: {{ .Values.api.containerPort }}
        - name: {{ .Values.metrics.portName | quote }}
          containerPort: {{ .Values.metrics.port }}
        env:
        {{- include "smartface.commonEnv" . | nindent 8 }}
        {{- include "smartface.dbConfig" . | nindent 8 }}
        {{- include "smartface.s3Config" . | nindent 8 }}
        {{- include "smartface.rmqConfig" . | nindent 8 }}
        {{- if and .Values.features.edgeStreams.enabled (or .Values.rabbitmq.enabled (not .Values.rabbitmq.mqttConfiguration.existingConfigMapName)) }}
        {{- include "smartface.mqttConfig" . | nindent 8 }}
        {{- end }}
        {{- include "smartface.apiFeaturesConfig" . | nindent 8 }}
        {{- include "smartface.statisticsPublish" . | nindent 8 }}
        - name: "Hosting__Host"
          value: "http://0.0.0.0"
        - name: "Hosting__Port"
          value: {{ .Values.api.containerPort | quote }}
        resources:
          {{- toYaml .Values.api.resources | nindent 10 }}
        volumeMounts:
        {{- include "smartface.licVolumeMount" . | nindent 8 }}
      {{- if and .Values.migration.enabled .Values.api.initMigration }}
      initContainers:
      {{- include "smartface.migrationInitContainer" . | nindent 6 }}
      {{- end }}
      volumes:
        {{- include "smartface.licVolume" . | nindent 8 }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
