{{- if .Values.authApi.enabled }}
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ .Values.authApi.name | quote }}
  labels:
    app: {{ .Values.authApi.name | quote }}
spec:
  {{- if not (and (or .Values.autoscaling.cron.enabled .Values.autoscaling.rmq.enabled) .Values.autoscaling.api.enabled ) }}
  replicas: {{ .Values.authApi.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.authApi.name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.authApi.name | quote }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | quote }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      topologySpreadConstraints:
        {{- include "smartface.topologySpread" (dict "appLabel" .Values.authApi.name) | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Values.authApi.name | quote }}
        image: {{ include "smartface.image" (dict "local" .Values.authApi.image "global" .Values.global.image "defaultVersion" .Chart.AppVersion) }}
        imagePullPolicy: {{ .Values.authApi.image.pullPolicy }}
        ports:
        - name: "http"
          containerPort: {{ .Values.authApi.containerPort }}
        - name: {{ .Values.metrics.portName | quote }}
          containerPort: {{ .Values.metrics.port }}
        env:
        {{- include "smartface.authenticationConfig" . | nindent 8 }}
        {{- include "smartface.commonEnv" . | nindent 8 }}
        {{- include "smartface.dbConfig" . | nindent 8 }}
        {{- include "smartface.s3Config" . | nindent 8 }}
        {{- include "smartface.rmqConfig" . | nindent 8 }}
        {{- include "smartface.apiFeaturesConfig" . | nindent 8 }}
        {{- include "smartface.statisticsPublish" . | nindent 8 }}
        - name: "Multitenancy__UseMultitenancy"
          value: {{ .Values.features.multitenancy.enabled | quote }}
        - name: "Hosting__Host"
          value: "http://0.0.0.0"
        - name: "Hosting__Port"
          value: {{ .Values.authApi.containerPort | quote }}
        resources:
          {{- toYaml .Values.authApi.resources | nindent 10 }}
        volumeMounts:
        {{- include "smartface.licVolumeMount" . | nindent 8 }}
      {{- if and .Values.migration.enabled .Values.authApi.initMigration }}
      initContainers:
      {{- include "smartface.migrationInitContainer" . | nindent 6 }}
      {{- end }}
      volumes:
        {{- include "smartface.licVolume" . | nindent 8 }}
      {{- with .Values.authApi.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.authApi.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
