{{- if .Values.countlyPublisher.enabled }}
apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "smartface.countlyPublisher.name" . | quote }}
  labels:
    {{- include "smartface.countlyPublisher.labels" . | nindent 4 }}
    {{- with .Values.serviceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.countlyPublisher.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.metrics.monitoring.serviceDiscoveryLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.countlyPublisher.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    {{- include "smartface.countlyPublisher.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.metrics.monitoring.portName | quote }}
      port: {{ .Values.metrics.monitoring.port }}
  type: "ClusterIP"
{{- end }}
