{{- if .Values.countlyPublisher.enabled }}
{{- $name := include "smartface.countlyPublisher.name" . -}}
{{- $selectorLabels := include "smartface.countlyPublisher.selectorLabels" . -}}
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ $name | quote }}
  labels:
    {{- include "smartface.countlyPublisher.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.countlyPublisher.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  {{- if .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- end }}
  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- $selectorLabels | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.countlyPublisher.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- $selectorLabels | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.countlyPublisher.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | quote }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      topologySpreadConstraints:
        {{- include "smartface.topologySpread" (dict "selectorLabels" $selectorLabels ) | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ $name | quote }}
        image: {{ include "smartface.image.noDefault" (dict "local" .Values.countlyPublisher.image "global" .Values.global.image) }}
        imagePullPolicy: {{ .Values.countlyPublisher.image.pullPolicy }}
        env:
        {{- include "smartface.commonEnv" . | nindent 8 }}
        {{- include "smartface.rmqConfig" . | nindent 8 }}
        - name: "CountlyConfiguration__ServerUrl"
          valueFrom:
            configMapKeyRef:
              name: countly-config
              key: url
        - name: "CountlyConfiguration__AppKey"
          valueFrom:
            secretKeyRef:
              name: counlty-app-key
              key: key
        - name: "CountlyConfiguration__AdditionalSegmentations__0__Key"
          value: "Cluster"
        - name: "CountlyConfiguration__AdditionalSegmentations__0__Value"
          value: {{ .Values.countlyPublisher.clusterName | quote }}
        - name: "PrometheusConfiguration__Endpoints__0"
          value: "http://+:{{ .Values.metrics.port }}/"
        resources:
          {{- toYaml .Values.countlyPublisher.resources | nindent 10 }}
      {{- with .Values.countlyPublisher.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.countlyPublisher.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
