{{- if and .Values.dbSynchronizationLeader.enabled .Values.features.multitenancy }}
{{- $name := include "smartface.dbSynchronizationLeader.name" . -}}
{{- $selectorLabels := include "smartface.dbSynchronizationLeader.selectorLabels" . -}}
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ $name | quote }}
  labels:
    {{- include "smartface.dbSynchronizationLeader.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.dbSynchronizationLeader.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.dbSynchronizationLeader.replicas }}
  selector:
    matchLabels:
      {{- $selectorLabels | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.dbSynchronizationLeader.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- $selectorLabels | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.dbSynchronizationLeader.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | quote }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      topologySpreadConstraints:
        {{- include "smartface.topologySpread" (dict "selectorLabels" $selectorLabels ) | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ $name | quote }}
        image: {{ include "smartface.image" (dict "local" .Values.dbSynchronizationLeader.image "global" .Values.global.image "defaultVersion" .Chart.AppVersion) }}
        imagePullPolicy: {{ .Values.dbSynchronizationLeader.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.dbSynchronizationLeader.containerPort }}
        env:
        {{- if .Values.dbSynchronizationLeader.enableAuth }}
        {{- include "smartface.authenticationConfig" . | nindent 8 }}
        {{- end }}
        {{- include "smartface.commonEnv" . | nindent 8 }}
        {{- include "smartface.dbConfig" . | nindent 8 }}
        {{- include "smartface.s3Config" . | nindent 8 }}
        {{- include "smartface.rmqConfig" . | nindent 8 }}
        - name: "Multitenancy__UseMultitenancy"
          value: {{ .Values.features.multitenancy.enabled | quote }}
        - name: "Hosting__Host"
          value: "http://0.0.0.0"
        - name: "Hosting__Port"
          value: {{ .Values.dbSynchronizationLeader.containerPort | quote }}
        resources:
          {{- toYaml .Values.dbSynchronizationLeader.resources | nindent 10 }}
        volumeMounts:
        {{- include "smartface.licVolumeMount" . | nindent 8 }}
      volumes:
        {{- include "smartface.licVolume" . | nindent 8 }}
      {{- with .Values.dbSynchronizationLeader.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dbSynchronizationLeader.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
