{{- $name := include "smartface.detector.name" . -}}
{{- $selectorLabels := include "smartface.detector.selectorLabels" . -}}
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ $name | quote }}
  labels:
    {{- include "smartface.detector.labels" . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.detector.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not (and (or .Values.autoscaling.cron.enabled .Values.autoscaling.rmq.enabled) .Values.autoscaling.detector.enabled ) }}
  replicas: {{ .Values.detector.replicas }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- $selectorLabels | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.detector.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- $selectorLabels | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.detector.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | quote }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      topologySpreadConstraints:
        {{- include "smartface.topologySpread" (dict "selectorLabels" $selectorLabels ) | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ $name | quote }}
        image: {{ include "smartface.image" (dict "local" .Values.detector.image "global" .Values.global.image "defaultVersion" .Chart.AppVersion) }}
        imagePullPolicy: {{ .Values.detector.image.pullPolicy }}
        env:
        {{- include "smartface.commonEnv" . | nindent 8 }}
        {{- include "smartface.rmqConfig" . | nindent 8 }}
        resources:
          {{- toYaml .Values.detector.resources | nindent 10 }}
        volumeMounts:
        {{- include "smartface.licVolumeMount" . | nindent 8 }}
      volumes:
        {{- include "smartface.licVolume" . | nindent 8 }}
      {{- with .Values.detector.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.detector.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
