{{- if .Values.graphqlApi.enabled }}
apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "smartface.graphqlApi.name" . | quote }}
  labels:
    {{- include "smartface.graphqlApi.labels" . | nindent 4 }}
    {{- with .Values.serviceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.graphqlApi.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.graphqlApi.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    {{- include "smartface.graphqlApi.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.graphqlApi.servicePort }}
      targetPort: {{ .Values.graphqlApi.containerPort }}
      {{- if eq .Values.graphqlApi.serviceType "NodePort" }}
      nodePort: {{ .Values.graphqlApi.nodePort }}
      {{- end }}
      protocol: "TCP"
  type: {{ .Values.graphqlApi.serviceType }}
{{- end }}
