apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ .Values.graphqlApi.name | quote }}
spec:
  selector:
    app: {{ .Values.graphqlApi.name | quote }}
  ports:
    - port: {{ .Values.graphqlApi.servicePort }}
      targetPort: {{ .Values.graphqlApi.containerPort }}
      protocol: "TCP"
  type: "NodePort"
