{{- if .Values.graphqlApi.enabled }}
{{- $name := include "smartface.graphqlApi.name" . -}}
{{- $selectorLabels := include "smartface.graphqlApi.selectorLabels" . -}}
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ $name | quote }}
  labels:
    {{- include "smartface.graphqlApi.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.graphqlApi.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.graphqlApi.replicas }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    type: {{ .Values.updateStrategy.type }}
  selector:
    matchLabels:
      {{- $selectorLabels | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.graphqlApi.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- $selectorLabels | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.graphqlApi.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | quote }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      topologySpreadConstraints:
        {{- include "smartface.topologySpread" (dict "selectorLabels" $selectorLabels ) | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ $name | quote }}
        image: {{ include "smartface.image" (dict "local" .Values.graphqlApi.image "global" .Values.global.image "defaultVersion" .Chart.AppVersion) }}
        imagePullPolicy: {{ .Values.graphqlApi.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.graphqlApi.containerPort }}
        env:
        {{- if .Values.graphqlApi.enableAuth }}
        {{- include "smartface.authenticationConfig" . | nindent 8 }}
        {{- end }}
        {{- include "smartface.commonEnv" . | nindent 8 }}
        {{- include "smartface.dbConfig" . | nindent 8 }}
        {{- include "smartface.s3Config" . | nindent 8 }}
        {{- include "smartface.rmqConfig" . | nindent 8 }}
        {{- if and .Values.features.edgeStreams.enabled (or .Values.rabbitmq.enabled (not .Values.rabbitmq.mqttConfiguration.existingConfigMapName)) }}
        {{- include "smartface.mqttConfig" . | nindent 8 }}
        {{- end }}
        - name: "Multitenancy__UseMultitenancy"
          value: {{ .Values.features.multitenancy.enabled | quote }}
        - name: "Hosting__Host"
          value: "http://0.0.0.0"
        - name: "Hosting__Port"
          value: {{ .Values.graphqlApi.containerPort | quote }}
        resources:
          {{- toYaml .Values.graphqlApi.resources | nindent 10 }}
        volumeMounts:
        {{- include "smartface.licVolumeMount" . | nindent 8 }}
      {{- if and .Values.migration.enabled .Values.graphqlApi.initMigration }}
      initContainers:
      {{- include "smartface.migrationInitContainer" . | nindent 6 }}
      {{- end }}
      volumes:
        {{- include "smartface.licVolume" . | nindent 8 }}
      {{- with .Values.graphqlApi.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.graphqlApi.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
