apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ .Values.graphqlApi.name | quote }}
  labels:
    app: {{ .Values.graphqlApi.name | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.graphqlApi.name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.graphqlApi.name | quote }}
    spec:
      topologySpreadConstraints:
        {{- include "sf-cloud-matcher.topologySpread" (dict "appLabel" .Values.graphqlApi.name) | nindent 8 }}
      imagePullSecrets:
      - name: {{ .Values.image.secretName | quote }}
      containers:
      - name: {{ .Values.graphqlApi.name | quote }}
        image: "{{ .Values.image.registry }}sf-graphql-api:{{ .Chart.AppVersion }}"
        ports:
        - containerPort: {{ .Values.graphqlApi.containerPort }}
        env:
        {{- if .Values.graphqlApi.enableAuth }}
        {{- include "sf-cloud-matcher.authenticationConfig" . | nindent 8 }}
        {{- end }}
        {{- include "sf-cloud-matcher.commonEnv" . | nindent 8 }}
        {{- include "sf-cloud-matcher.dbConfig" . | nindent 8 }}
        {{- include "sf-cloud-matcher.s3Config" . | nindent 8 }}
        {{- include "sf-cloud-matcher.rmqConfig" . | nindent 8 }}
        {{- include "sf-cloud-matcher.apiFeaturesConfig" . | nindent 8 }}
        - name: "Multitenancy__UseMultitenancy"
          value: {{ .Values.multitenancy.enabled | quote }}
        - name: "Hosting__Host"
          value: "http://0.0.0.0"
        - name: "Hosting__Port"
          value: {{ .Values.graphqlApi.containerPort | quote }}
        resources:
          {{- toYaml .Values.graphqlApi.resources | nindent 10 }}
        volumeMounts:
        {{- include "sf-cloud-matcher.licVolumeMount" . | nindent 8 }}
      {{- if and .Values.migration.enabled .Values.graphqlApi.initMigration }}
      initContainers:
      {{- include "sf-cloud-matcher.migrationInitContainer" . | nindent 6 }}
      {{- end }}
      volumes:
        {{- include "sf-cloud-matcher.licVolume" . | nindent 8 }}
