{{- if .Values.ingress.enabled }}
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "sf-ingress"
  annotations:
    {{- if .Values.ingress.includeAlbAnnotations }}
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    {{- if .Values.ingress.certificateArn }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateArn }}
    {{- end }}
    {{- end }}
    {{- if .Values.ingress.annotations }}
    {{- toYaml $.Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.class }}
  ingressClassName: {{ .Values.ingress.class | quote }}
  {{- end }}
  rules:
    {{- if .Values.api.enabled }}
    - host: {{ .Values.api.dnsHost }}
      http:
        paths:
        - path: "/"
          pathType: "Prefix"
          backend:
            service:
              {{- if .Values.readonlyApi.enabled }}
              name: {{ .Values.readonlyApi.noAuthName | quote }}
              {{- else }}
              name: {{ .Values.api.name | quote }}
              {{- end }}
              port:
                number: {{ .Values.api.servicePort }}
    {{- end }}
    {{- if .Values.authApi.enabled }}
    - host: {{ .Values.authApi.dnsHost }}
      http:
        paths:
        - path: "/"
          pathType: "Prefix"
          backend:
            service:
              {{- if .Values.readonlyApi.enabled }}
              name: {{ .Values.readonlyApi.authName | quote }}
              {{- else }}
              name: {{ .Values.authApi.name | quote }}
              {{- end }}
              port:
                number: {{ .Values.authApi.servicePort }}
    {{- end }}
    {{- if .Values.graphqlApi.enabled }}
    - host: {{ .Values.graphqlApi.dnsHost }}
      http:
        paths:
        - path: "/"
          pathType: "Prefix"
          backend:
            service:
              name: {{ .Values.graphqlApi.name | quote }}
              port:
                number: {{ .Values.graphqlApi.servicePort }}
    {{- end }}
    {{- if .Values.station.enabled }}
    - host: {{ .Values.station.dnsHost }}
      http:
        paths:
        - path: "/"
          pathType: "Prefix"
          backend:
            service:
              name: {{ .Values.station.name | quote }}
              port:
                number: {{ .Values.station.servicePort }}
    {{- end }}
{{- end }}
