{{- if .Values.features.multitenancy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
# we use index bacuse of https://github.com/helm/helm/issues/2192
  name: {{ index .Values "sf-tenant-operator" "config" "mapName" | quote }}
data:
  {{ index .Values "sf-tenant-operator" "config" "fileName" }}: |-
    {
      "LoopConfiguration": {
        "FullFetchLoopDelay": "00:00:30"
      },
      "ReconciliationConfiguration": {
        "Namespace": "{{ .Release.Namespace }}",
        "Deployments": [
          {
            "ComponentName": "matcher",
            "DeploymentTemplateFilePath": "{{ index .Values "sf-tenant-operator" "config" "configDir" }}/matcher.yaml",
            "TenantEnvVar": "Multitenancy__TenantId"
          }
        ],
        "Jobs": [
          {
            {{- if or .Values.features.edgeStreams.enabled .Values.dbSynchronizationLeader.enabled }}
            "Name": "wl_stream_population_job",
            "TemplateFilePath": "{{ index .Values "sf-tenant-operator" "config" "configDir" }}/wlStreamPopulationJob.yaml",
            "SubmittedAnnotationName": "WlStreamSubmitted",
            "TenantEnvVar": "Multitenancy__TenantId",
            "JobIdEnvVar": "GENERATION_ID"
            {{- end}}
          }
        ]
      }
    }
  matcher.yaml: |-
    {{- include "smartface.matcherDefinition" . | nindent 4 }}
  wlStreamPopulationJob.yaml: |-
    {{- include "smartface.wlStreamPopulationJob" . | nindent 4}}
{{- end}}
