{{- if .Values.station.enabled }}
apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "smartface.station.name" . | quote }}
  labels:
    {{- include "smartface.station.labels" . | nindent 4 }}
    {{- with .Values.serviceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.station.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.station.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    {{- include "smartface.station.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.station.servicePort }}
      targetPort: {{ .Values.station.containerPort }}
      protocol: "TCP"
  type: "ClusterIP"
{{- end }}
