features:
  edgeStreams:
    enabled: true

# edge stream tests test WL sync, which requires the population job to be run
edgeStreamsStateSync:
  resources: null
  wlStreamPopulationJob:
    enabled: true
