# we don't need persistence since the kind cluster will be deleted after the tests anyway
rabbitmq:
  persistence:
    enabled: false
postgresql:
  primary:
    persistence:
      enabled: false
minio:
  persistence:
    enabled: false

configurations:
  apiAuth:
    authority: "https://smartface-test.eu.auth0.com"
    audience: "https://api.ghaction.smartfacecloud.com"
    oauthTokenUrl: "https://smartface-test.eu.auth0.com/oauth/token"
tests:
  authentication:
    tenant1:
      name: "tenant-1"
      clientId: "ZwZ71smcNTpCLHdqJNkMeLy2kM6cDwQY"
    tenant2:
      name: "tenant-2"
      clientId: "guwK5NNDOj8hzYXfnJFVq4ZtuLx8RUTZ"
api:
  resources: null
authApi:
  enabled: true
  resources: null
graphqlApi:
  enableAuth: true
  resources: null
detector:
  resources: null
extractor:
  resources: null
matcher:
  resources: null
liveness:
  resources: null
edgeStreamProcessor:
  resources: null
# edge stream tests test WL sync, which requires the population job to be run
edgeStreamsStateSync:
  resources: null
  wlStreamPopulationJob:
    enabled: true
base:
  resources: null
faceMatcher:
  resources: null
accessController:
  resources: null
streamDataDbWorker:
  resources: null
