{{- if .Values.features.edgeStreams.enabled }}
apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "smartface.accessController.name" . | quote }}
  labels:
    {{- include "smartface.accessController.labels" . | nindent 4 }}
    {{- with .Values.serviceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.api.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.accessController.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    {{- include "smartface.accessController.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.accessController.servicePort }}
      targetPort: {{ .Values.accessController.containerPort }}
      protocol: "TCP"
  type: "ClusterIP"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "smartface.accessController.authServiceName" . | quote }}
  labels:
    {{- include "smartface.accessController.labels" . | nindent 4 }}
    {{- with .Values.serviceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.api.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.accessController.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    {{- include "smartface.accessController.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.accessController.authServicePort }}
      targetPort: {{ .Values.accessController.authContainerPort }}
      protocol: "TCP"
  type: "ClusterIP"
{{- end }}
