{{- if .Values.features.edgeStreams.enabled }}
{{- $name := include "smartface.accessController.name" . -}}
{{- $selectorLabels := include "smartface.accessController.selectorLabels" . -}}
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ $name | quote }}
  labels:
    {{- include "smartface.accessController.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.accessController.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  {{- if .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- end }}
  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- $selectorLabels | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.accessController.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- $selectorLabels | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.accessController.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | quote }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      topologySpreadConstraints:
        {{- include "smartface.topologySpread" (dict "selectorLabels" $selectorLabels ) | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ $name | quote }}
        image: {{ include "smartface.image" (dict "local" .Values.accessController.image "global" .Values.global.image "defaultVersion" .Chart.AppVersion) }}
        imagePullPolicy: {{ .Values.accessController.image.pullPolicy }}
        env:
        {{- include "smartface.commonEnv" . | nindent 8 }}
        {{- include "smartface.rmqConfig" . | nindent 8 }}
        {{- include "smartface.mqttConfig" . | nindent 8 }}
        {{- include "smartface.authenticationConfig" . | nindent 8 }}
        {{- include "smartface.mqttConfig" . | nindent 8 }}
        - name: "Kestrel__EndPoints__Http__Url"
          value: "http://0.0.0.0:{{ .Values.accessController.containerPort }}"
        - name: "Kestrel__EndPoints__Http__RequireAuthentication"
          value: "false"
        - name: "Kestrel__EndPoints__HttpAuth__Url"
          value: "http://0.0.0.0:{{ .Values.accessController.authContainerPort }}"
        - name: "Kestrel__EndPoints__HttpAuth__RequireAuthentication"
          value: "true"
        - name: "MQTT__Enabled"
          value: {{ .Values.accessController.mqttConfig.enabled | quote }}
        - name: "MQTT__Topic"
          value: {{ .Values.accessController.mqttConfig.topic | quote }}
        - name: "MQTT__SendImageData"
          value: {{ .Values.accessController.mqttConfig.sendImageData | quote }}

        - name: "FilterConfiguration__FaceOrderConfiguration__Enabled"
          value: {{ .Values.accessController.filterConfiguration.faceOrderConfiguration.enabled | quote }}
        - name: "FilterConfiguration__FaceOrderConfiguration__Order"
          value: {{ .Values.accessController.filterConfiguration.faceOrderConfiguration.order | quote }}
        - name: "FilterConfiguration__OpeningDebounceConfiguration__OpeningDebounceEnabled"
          value: {{ .Values.accessController.filterConfiguration.openingDebounceConfiguration.openingDebounceEnabled | quote }}
        - name: "FilterConfiguration__OpeningDebounceConfiguration__OpeningDebounceMs"
          value: {{ .Values.accessController.filterConfiguration.openingDebounceConfiguration.openingDebounceMs | quote }}
        - name: "FilterConfiguration__SpoofCheckConfiguration__Enabled"
          value: {{ .Values.accessController.filterConfiguration.spoofCheckConfiguration.enabled | quote }}
        - name: "FilterConfiguration__SpoofCheckConfiguration__DenyingDebounceMs"
          value: {{ .Values.accessController.filterConfiguration.spoofCheckConfiguration.denyingDebounceMs | quote }}
        resources:
          {{- toYaml .Values.accessController.resources | nindent 10 }}
        volumeMounts:
        {{- include "smartface.licVolumeMount" . | nindent 8 }}
      volumes:
        {{- include "smartface.licVolume" . | nindent 8 }}
      {{- with .Values.accessController.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.accessController.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
