{{- if .Values.edgeStreams.enabled }}
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ .Values.accessController.name | quote }}
  labels:
    app: {{ .Values.accessController.name | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.accessController.name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.accessController.name | quote }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | quote }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      topologySpreadConstraints:
        {{- include "smartface.topologySpread" (dict "appLabel" .Values.accessController.name) | nindent 8 }}
      imagePullSecrets:
      - name: {{ .Values.image.secretName | quote }}
      containers:
      - name: {{ .Values.accessController.name | quote }}
        image: "{{ .Values.image.registry }}sf-access-controller:{{ .Values.accessController.imageVersion }}"
        env:
        {{- include "smartface.commonEnv" . | nindent 8 }}
        {{- include "smartface.rmqConfig" . | nindent 8 }}
        {{- include "smartface.authenticationConfig" . | nindent 8 }}
        - name: "Kestrel__EndPoints__Http__Url"
          value: "http://0.0.0.0:{{ .Values.accessController.containerPort }}"
        - name: "Kestrel__EndPoints__Http__RequireAuthentication"
          value: "false"
        - name: "Kestrel__EndPoints__HttpAuth__Url"
          value: "http://0.0.0.0:{{ .Values.accessController.authContainerPort }}"
        - name: "Kestrel__EndPoints__HttpAuth__RequireAuthentication"
          value: "true"
        resources:
          {{- toYaml .Values.accessController.resources | nindent 10 }}
        volumeMounts:
        {{- include "smartface.licVolumeMount" . | nindent 8 }}
      volumes:
        {{- include "smartface.licVolume" . | nindent 8 }}
      {{- with .Values.accessController.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.accessController.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
