{{- if .Values.features.edgeStreams.enabled }}
apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ .Values.base.name | quote }}
spec:
  selector:
    app: {{ .Values.base.name | quote }}
  ports:
    - port: {{ .Values.base.zmqServicePort }}
      targetPort: {{ .Values.base.zmqContainerPort }}
      protocol: "TCP"
  type: "NodePort"
{{- end }}
