name: Package and lint

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup helm CLI
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build helm dependencies
        run: |
          helm dependency build .
      - name: Lint helm
        run: |
          helm lint .
      # we package just to validate
      - name: Package helm
        run: |
          helm package .
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
