name: Package and lint

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
    paths-ignore:
      - "*.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup helm CLI
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      # This is only needed temporarily until the tenant-operator package is public, but we will need this code for pushing
      - name: Helm login to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username ${{ github.repository_owner }} --password-stdin
      - name: Build helm dependencies
        run: |
          helm dependency build .
      - name: Lint helm
        run: |
          helm lint .
      # we package just to validate
      - name: package helm
        run: |
          helm package .
